### ISSUE TITLE
Github Workflow backup does not start an action

### ISSUE THREAD

**Issue by IanQS** [MatthieuBizien/roam-to-git#37]
**Describe the bug**

I've followed all the instructions but when I push the repo I do not see anything being run in the "Actions" tab.

**To Reproduce**

1) Create a new private repo
2) Add secrets like in the `env.template` (but obviously I changed it to my credentials)
3) Add the github action
4) Check that the github action works

- It has been 15 minutes and my github action has not yet kicked off yet. As far as I can tell nothing has run and I don't know if there are any debug logs that I can look for? 

**Expected behavior**
Backup action to run

**Traceback**

- None? I'm using Github actions 

**Please complete the following information:**
- OS: [e.g. MacOs, Linux] Linux
- Do you use Github Action? Yes
- Do you use multiple Roam databases? No
- Does roam-to-git use to work for you? When precisely did it stopped to work? Haven't done it - I assume I can do either method and that I don't need to use the local one to get the actions to run
- Does some backup runs are still working? Nope

**Additional context**

---

My directory structure looks like this

```
my_dir/
  | .github/
    | workflows/
      | main.yml
  | .git
```

where my `main.yml` contains 

```
name: "Roam Research backup"

on:
  push:
    branches:
      - master
  schedule:
    -   cron: "0 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 15
    steps:
      -   uses: actions/checkout@v2
      -   name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

      -   name: Setup dependencies
          run: |
            pip install git+https://github.com/MatthieuBizien/roam-to-git.git
      -   name: Run backup
          run: roam-to-git --skip-git .
          env:
            ROAMRESEARCH_USER: ${{ secrets.ROAMRESEARCH_USER }}
            ROAMRESEARCH_PASSWORD: ${{ secrets.ROAMRESEARCH_PASSWORD }}
            ROAMRESEARCH_DATABASE: ${{ secrets.ROAMRESEARCH_DATABASE }}

      -   name: Commit changes
          uses: elstudio/actions-js-build/commit@v3
          with:
            commitMessage: Automated snapshot
```
