### ISSUE TITLE
Suggestion: use Github actions to execute backup & commit changes to the repository

### ISSUE THREAD

**Issue by Stvad** [MatthieuBizien/roam-to-git#4]
The alternative backup implementation: https://github.com/signalnerve/roam-backup does that, and it seems like a pretty great way to go about - it's free & there are already workflow templates to checkout/update repository.

**Comment by Stvad** [comment]
https://github.com/elstudio/actions-js-build/tree/master/commit has an example workflow

**Comment by Stvad** [comment]
this is close to working

```
name: "Roam Research backup"

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/10 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Setup dependencies
        run: |
          pip install git+https://github.com/MatthieuBizien/roam-to-git.git
      - name: Run backup
        run: roam-to-git --skip-git .
        env:
          ROAMRESEARCH_USER: ${{ secrets.roamEmail }}
          ROAMRESEARCH_PASSWORD: ${{ secrets.roamPassword }}
          ROAMRESEARCH_DATABASE: ${{ secrets.roamDatabase }}
          
      - name: Commit changes
        uses: elstudio/actions-js-build/commit@v3
        with:
          commitMessage: Automated snapshot
```
